// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Ki33MJzSW4QyOer9nrBGG5TpHXWRZV8',
    appId: '1:771761409760:web:3467fb97fb474d9e168a85',
    messagingSenderId: '771761409760',
    projectId: 'talabat-like-app',
    authDomain: 'talabat-like-app.firebaseapp.com',
    storageBucket: 'talabat-like-app.firebasestorage.app',
    measurementId: 'G-H10ZVTWCEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3HW0CfscgFFu5Lxh1tJpNcHy_jqlsUB4',
    appId: '1:771761409760:android:04436a228dc1edc4168a85',
    messagingSenderId: '771761409760',
    projectId: 'talabat-like-app',
    storageBucket: 'talabat-like-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9M556Zed435OSs3B18B9_x-N7Ci-OPu0',
    appId: '1:771761409760:ios:44d9da40c2227e5a168a85',
    messagingSenderId: '771761409760',
    projectId: 'talabat-like-app',
    storageBucket: 'talabat-like-app.firebasestorage.app',
    iosBundleId: 'com.example.task1Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9M556Zed435OSs3B18B9_x-N7Ci-OPu0',
    appId: '1:771761409760:ios:44d9da40c2227e5a168a85',
    messagingSenderId: '771761409760',
    projectId: 'talabat-like-app',
    storageBucket: 'talabat-like-app.firebasestorage.app',
    iosBundleId: 'com.example.task1Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Ki33MJzSW4QyOer9nrBGG5TpHXWRZV8',
    appId: '1:771761409760:web:490b3803b4bef957168a85',
    messagingSenderId: '771761409760',
    projectId: 'talabat-like-app',
    authDomain: 'talabat-like-app.firebaseapp.com',
    storageBucket: 'talabat-like-app.firebasestorage.app',
    measurementId: 'G-7RTQHQ92E4',
  );
}
